name: Node.js CI with SonarQube

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SonarQube
        uses: SonarSource/setup-sonarqube@v1
        with:
          project-key: ${{ github.repository }}
          project-name: ${{ github.repository }}
          project-version: 1.0
          server-url: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarQube analysis
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner
        env:
          SONAR_USER_HOME: ${{ runner.temp }}/.sonar
