name: Node.js CI with SonarQube

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust the Node.js version as needed

  sonarqube:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Set up SonarQube
      uses: SonarSource/sonarcloud-github-action@master
      with:
        organization: your-organization-key  # Replace with your organization key
        token: ${{ secrets.SONARQUBE_TOKEN }}

    - name: Run SonarQube analysis
      run: sonar-scanner
