name: SonarQube Analysis

on:
  push:
    branches:
      - main # Change to your project's main branch

jobs:
  sonarqube:
    runs-on: windows-latest # Use the Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change to your desired Node.js version

    - name: Install project dependencies
      run: npm install

    - name: Download and extract SonarScanner
      run: |
        # Download SonarScanner (replace with the latest version)
        Invoke-WebRequest -Uri 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.2.2564-windows.zip' -OutFile 'sonar-scanner.zip'
        Expand-Archive -Path 'sonar-scanner.zip' -DestinationPath $Env:USERPROFILE
        $scannerDir = Join-Path $Env:USERPROFILE 'sonar-scanner-4.7.2.2564-windows'
        Write-Output "##vso[task.setvariable variable=SCANNER_DIR]$scannerDir"
      shell: pwsh

    - name: Run SonarQube analysis
      run: |
        $scannerDir = $Env:SCANNER_DIR
        $scannerExe = Join-Path $scannerDir 'bin\sonar-scanner.bat'
        & $scannerExe
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Replace with your SonarQube token
        SONAR_HOST_URL: http://your-sonarqube-server:9000 # Replace with your SonarQube server URL
