name: SonarQube Analysis

on:
  push:
    branches:
      - main # Change this to your project's main branch

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change to your desired Node.js version

    - name: Install project dependencies
      run: npm install

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@main
      env:
    
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Replace with your SonarQube token
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
