name: SonarQube Analysis

on:
  push:
    branches:
      - main # Change to your project's main branch

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change to your desired Node.js version

    - name: Install project dependencies
      run: npm install

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
    
        SONAR_TOKEN: squ_546542a50c646fd94274ccc878e9de56402e1ecb
        SONAR_HOST_URL: http://localhost:9000/
